# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import calculadora as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    calculadora_0 = module_0.Calculadora()
    calculadora_1 = module_0.Calculadora()
    calculadora_0.dividir(calculadora_1, calculadora_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    calculadora_0 = module_0.Calculadora()
    calculadora_0.sumar(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    calculadora_0 = module_0.Calculadora()
    set_0 = set()
    list_0 = []
    list_1 = [list_0, list_0]
    calculadora_0.multiplicar(set_0, list_1)


@pytest.mark.xfail(strict=True)
def test_case_3():
    set_0 = set()
    calculadora_0 = module_0.Calculadora()
    calculadora_0.potencia(set_0, set_0)


def test_case_4():
    float_0 = -3910.818689
    calculadora_0 = module_0.Calculadora()
    var_0 = calculadora_0.es_par(float_0)
    assert var_0 is False


def test_case_5():
    int_0 = -2013
    calculadora_0 = module_0.Calculadora()
    var_0 = calculadora_0.restar(int_0, int_0)
    assert var_0 == 0
    none_type_0 = None
    with pytest.raises(ValueError):
        calculadora_0.dividir(none_type_0, var_0)
