# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import validador_edad as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.clasificar_edad(bool_0)
    assert var_0 == "niño"
    var_1 = module_0.es_mayor_de_edad(bool_0)
    assert var_1 is False


def test_case_1():
    int_0 = 19
    var_0 = module_0.clasificar_edad(int_0)
    assert var_0 == "adulto mayor"


def test_case_2():
    int_0 = 3708
    var_0 = module_0.es_mayor_de_edad(int_0)
    assert var_0 is True
    var_1 = module_0.clasificar_edad(int_0)
    assert var_1 == "desconocido"


def test_case_3():
    int_0 = 18
    var_0 = module_0.es_mayor_de_edad(int_0)
    assert var_0 is False
    var_1 = module_0.clasificar_edad(int_0)
    assert var_1 == "adolescente"
